// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBwoasjAIxn0XY7Fd83N-ypC4DddaS-0',
    appId: '1:864468840662:web:976da670d200f7b6929977',
    messagingSenderId: '864468840662',
    projectId: 'tintnotes',
    authDomain: 'tintnotes.firebaseapp.com',
    storageBucket: 'tintnotes.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrBwoasjAIxn0XY7Fd83N-ypC4DddaS-0',
    appId: '1:864468840662:android:976da670d200f7b6929977',
    messagingSenderId: '864468840662',
    projectId: 'tintnotes',
    storageBucket: 'tintnotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrBwoasjAIxn0XY7Fd83N-ypC4DddaS-0',
    appId: '1:864468840662:ios:976da670d200f7b6929977',
    messagingSenderId: '864468840662',
    projectId: 'tintnotes',
    iosClientId: '864468840662-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.inksync.inksync',
    storageBucket: 'tintnotes.firebasestorage.app',
  );
}
