name: Build Android App Bundle (AAB)

on:
  workflow_dispatch: # Allows you to manually trigger a build from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Cache Android Keystore
        uses: actions/cache@v4
        with:
          path: ~/.android/debug.keystore
          key: android-debug-keystore

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: inksync-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
